/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.util.Objects;
import javax.swing.ImageIcon;
import model.UserProfile;

/**
 *
 * @author Mital
 */
public class viewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewJPanel
     */
    
    UserProfile profile;
    
    public viewJPanel(UserProfile profile) {
        initComponents();
        this.profile = profile;
        displayProfileInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblGeoData = new javax.swing.JLabel();
        txtGeoData = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        lblTeleNo = new javax.swing.JLabel();
        txtTeleNo = new javax.swing.JTextField();
        lblFaxNo = new javax.swing.JLabel();
        txtFaxNo = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtSSNNo = new javax.swing.JTextField();
        lblMedRecNo = new javax.swing.JLabel();
        txtMedicalNo = new javax.swing.JTextField();
        lblHealthPlanNo = new javax.swing.JLabel();
        txtHealthPlanNo = new javax.swing.JTextField();
        lblAccNo = new javax.swing.JLabel();
        txtBankAccNo = new javax.swing.JTextField();
        lblLicenseNo = new javax.swing.JLabel();
        txtCertificateNo = new javax.swing.JTextField();
        lblVehNo = new javax.swing.JLabel();
        txtVehicleNo = new javax.swing.JTextField();
        lblDeviceNo = new javax.swing.JLabel();
        txtDeviceNo = new javax.swing.JTextField();
        lblLinkedIn = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JTextField();
        lblIPAdd = new javax.swing.JLabel();
        txtIPAdd = new javax.swing.JTextField();
        lblBioMetric = new javax.swing.JLabel();
        lblPhotoId = new javax.swing.JLabel();
        lblUniqueIdNo = new javax.swing.JLabel();
        txtUniqueIdNo = new javax.swing.JTextField();
        lblBiometricImage = new javax.swing.JLabel();
        lblFacePhotoImage = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(824, 698));

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("View Profile");

        lblName.setText("Name :");

        lblGeoData.setText("Geographic Data :");

        lblDOB.setText("Date Of Birth :");

        lblTeleNo.setText("Telephone No :");

        lblFaxNo.setText("Fax Number :");

        lblEmail.setText("Email Address :");

        lblSSN.setText("Social Security Number :");

        lblMedRecNo.setText("Medical Record Number :");

        lblHealthPlanNo.setText("Health Plan Beneficiary Number :");

        lblAccNo.setText("Bank Account Number :");

        lblLicenseNo.setText("Certificate/License Number :");

        lblVehNo.setText("Vehicle Identifiers :");

        lblDeviceNo.setText("Device Identifiers :");

        lblLinkedIn.setText("LinkedIn :");

        lblIPAdd.setText("Internet Protocol Address :");

        lblBioMetric.setText("Biometric Identifiers :");

        lblPhotoId.setText("Full Face Photo :");

        lblUniqueIdNo.setText("Unique Identifying Number :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMedRecNo)
                            .addComponent(lblSSN)
                            .addComponent(lblEmail)
                            .addComponent(lblFaxNo)
                            .addComponent(lblTeleNo)
                            .addComponent(lblDOB)
                            .addComponent(lblGeoData)
                            .addComponent(lblName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtGeoData)
                            .addComponent(txtTeleNo)
                            .addComponent(txtFaxNo)
                            .addComponent(txtEmail)
                            .addComponent(txtSSNNo)
                            .addComponent(txtMedicalNo)
                            .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblUniqueIdNo)
                                .addGap(18, 18, 18)
                                .addComponent(txtUniqueIdNo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblIPAdd)
                                    .addComponent(lblLinkedIn)
                                    .addComponent(lblDeviceNo)
                                    .addComponent(lblVehNo)
                                    .addComponent(lblLicenseNo)
                                    .addComponent(lblAccNo)
                                    .addComponent(lblBioMetric)
                                    .addComponent(lblPhotoId)
                                    .addComponent(lblHealthPlanNo))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtCertificateNo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDeviceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBankAccNo, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                            .addComponent(txtIPAdd)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHealthPlanNo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFacePhotoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblBiometricImage, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeoData)
                    .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeleNo)
                    .addComponent(txtTeleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNo)
                    .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSNNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedRecNo)
                    .addComponent(txtMedicalNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHealthPlanNo)
                    .addComponent(txtHealthPlanNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccNo)
                    .addComponent(txtBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNo)
                    .addComponent(txtCertificateNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehNo)
                    .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceNo)
                    .addComponent(txtDeviceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedIn)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPAdd)
                    .addComponent(txtIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBioMetric)
                    .addComponent(lblBiometricImage, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhotoId)
                    .addComponent(lblFacePhotoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniqueIdNo)
                    .addComponent(txtUniqueIdNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblBioMetric;
    private javax.swing.JLabel lblBiometricImage;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceNo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFacePhotoImage;
    private javax.swing.JLabel lblFaxNo;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHealthPlanNo;
    private javax.swing.JLabel lblIPAdd;
    private javax.swing.JLabel lblLicenseNo;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedRecNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhotoId;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTeleNo;
    private javax.swing.JLabel lblUniqueIdNo;
    private javax.swing.JLabel lblVehNo;
    private javax.swing.JTextField txtBankAccNo;
    private javax.swing.JTextField txtCertificateNo;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDeviceNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealthPlanNo;
    private javax.swing.JTextField txtIPAdd;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSNNo;
    private javax.swing.JTextField txtTeleNo;
    private javax.swing.JTextField txtUniqueIdNo;
    private javax.swing.JTextField txtVehicleNo;
    // End of variables declaration//GEN-END:variables

    private void displayProfileInfo() {
     txtName.setText(profile.getName());
     txtGeoData.setText(profile.getGeodata());
     txtDOB.setText(profile.getDob()); 
     if(profile.getTeleNumber() != null)
     {
        txtTeleNo.setText(Long.toString(profile.getTeleNumber()));
     }
     if(profile.getFaxNo()!= null)
     {
        txtFaxNo.setText(Long.toString(profile.getFaxNo()));
     }
     txtEmail.setText(profile.getEmailId());
     txtSSNNo.setText(profile.getSsnNo());
     if(profile.getMedRecNo() != null)
     {
        txtMedicalNo.setText(Long.toString(profile.getMedRecNo()));
     }
     if(profile.getHealthPlanNo()!= null)
     {
        txtHealthPlanNo.setText(Long.toString(profile.getHealthPlanNo()));
     }
     if(profile.getBankAccNo() != null)
     {
        txtBankAccNo.setText(Long.toString(profile.getBankAccNo()));
     }
     txtCertificateNo.setText(profile.getLicenseNo());
     txtVehicleNo.setText(profile.getVehId());
     txtDeviceNo.setText(profile.getDeviceId());
     txtLinkedIn.setText(profile.getLinkedIn());
     txtIPAdd.setText(profile.getIpAdd());
     ImageIcon biometricIcon = new ImageIcon(profile.getBiometricFileName());
     Image biometricImage = biometricIcon.getImage().getScaledInstance(500,500,Image.SCALE_SMOOTH);
     lblBiometricImage.setIcon(new ImageIcon(biometricImage));
     ImageIcon profileIcon = new ImageIcon(profile.getPhotoFileName());
     Image profileImage = profileIcon.getImage().getScaledInstance(500,500,Image.SCALE_SMOOTH);
     lblFacePhotoImage.setIcon(new ImageIcon(profileImage));
     txtUniqueIdNo.setText(profile.getUniqueNo());
    }
}
